name: hondooye_design_system
description: hondooye design system
version: 0.0.1
repository: "https://github.com/Doohyeon-Kim/hondooye-design-system.git"

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: SFPro
      fonts:
        - asset: lib/fonts/sf_pro/SF-Pro.ttf
    - family: AppleSDGothicNeo
      fonts:
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoT.ttf
          weight: 100
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoUL.ttf
          weight: 200
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoSB.ttf
          weight: 600
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoEB.ttf
          weight: 800
        - asset: lib/fonts/apple_sd_gothic_neo/AppleSDGothicNeoH.ttf
          weight: 900
    - family: NotoSansKR
      fonts:
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Thin.otf
          weight: 100
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Regular.otf
          weight: 400
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: lib/fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900
    - family: Roboto
      fonts:
        - asset: lib/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: lib/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: lib/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: lib/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: lib/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: lib/fonts/roboto/Roboto-Black.ttf
          weight: 900