import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF7049AC),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFECDCFF),
  onPrimaryContainer: Color(0xFF270057),
  secondary: Color(0xFF645B70),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFEADEF7),
  onSecondaryContainer: Color(0xFF1F182A),
  tertiary: Color(0xFF7F525C),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFD9E0),
  onTertiaryContainer: Color(0xFF32101A),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE8E0EB),
  onSurfaceVariant: Color(0xFF49454E),
  outline: Color(0xFF7B757F),
  onInverseSurface: Color(0xFFF5EFF4),
  inverseSurface: Color(0xFF323033),
  inversePrimary: Color(0xFFD5BAFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF7049AC),
  // outlineVariant: Color(0xFFCBC4CF),
  // scrim: Color(0xFF000000),
);

